spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm_database
    username: your_postgres_username
    password: your_postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: your_very_long_and_complex_secret_key_for_jwt
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG